### ISSUE TITLE
A JavaScript error occurred in the main process (Ubuntu 16.04 Gnome)

### ISSUE THREAD

**Issue by lucianosb** [vincelwt/harmony#133]
I'm not sure what is happening here. I'm getting the following error while trying to launch Harmony.

> Uncaught Exception:
> TypeError: Error processing argument at index 0, conversion failure from #<Object>
>     at TypeError (native)
>     at validateState (/opt/Harmony/resources/app/node_modules/electron-window-state/index.js:46:34)
>     at module.exports (/opt/Harmony/resources/app/node_modules/electron-window-state/index.js:154:3)
>     at App.createWindow (/opt/Harmony/resources/app/main.js:18:24)
>     at emitTwo (events.js:111:20)
>     at App.emit (events.js:191:7)

**Comment by vincelwt** [comment]
Hi,
Is this happening when trying to launch with the .AppImage or after installing with the deb package?

**Comment by lucianosb** [comment]
With the deb package at first. Then I tried the AppImage and it happened again.

**Comment by vincelwt** [comment]
Is this error still happening with latest releases ?
