### ISSUE TITLE
Windows/Linux media key support

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#14]
Harmony doesn't have support for physical media keys, or support for keyboard shortcuts.

**Comment by vincelwt** [comment]
Hi @NickFlamel 

Harmony should supports media keys (on Mac) and provide a bunch of keyboard shortcuts:

Space -> Play/Pause
N or Ctrl/Cmd + Right -> Next track
P or Ctrl/Cmd + Left -> Prev track
L -> Like track
Ctrl/Cmd + F -> Search

Are you using a Mac ?

**Comment by NickFlamel** [comment]
No, I'm using Windows. Here's the keyboard I'm using: [http://www.coolermaster.com/peripheral/keyboards/octane/](url) I guess I meant universal media shortcuts, so I can change songs when I'm not in Harmony.

**Comment by vincelwt** [comment]
Well, this is based on [this plugin](https://github.com/tcr/mediakeys) so it should works. I will make some tests when I can access a Windows computer

**Comment by lfer123** [comment]
Keyboard shortcuts works well on Windows. However, my physical media keys doesn't work.

**Comment by icd13** [comment]
This fixed now?

**Comment by vincelwt** [comment]
@icd13 Nop, there is a problem with the mediakeys plugin build on windows.

Output from AppVeyor:

```
> mediakeys@0.1.1 install C:\projects\harmony\node_modules\mediakeys
> node-gyp rebuild
C:\projects\harmony\node_modules\mediakeys>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  MMShellHook.cpp
  win_delay_load_hook.cc
     Creating library C:\projects\harmony\node_modules\mediakeys\build\Release\MMShellHook.lib and object C:\projects\harmony\node_modules\mediakeys\build\Release\MMShellHook.exp
win_delay_load_hook.obj : error LNK2001: unresolved external symbol __stricmp [C:\projects\harmony\node_modules\mediakeys\build\win\MMShellHook.vcxproj]
C:\projects\harmony\node_modules\mediakeys\build\Release\MMShellHook.dll : fatal error LNK1120: 1 unresolved externals [C:\projects\harmony\node_modules\mediakeys\build\win\MMShellHook.vcxproj]
  win.cpp
  win_delay_load_hook.cc
win.obj : warning LNK4258: directive '/ENTRY:mainCRTStartup' not compatible with switch '/ENTRY:WinMainCRTStartup'; ignored [C:\projects\harmony\node_modules\mediakeys\build\win\keylistener.vcxproj]
  Generating code
  Finished generating code
  keylistener.vcxproj -> C:\projects\harmony\node_modules\mediakeys\build\Release\\keylistener.exe
  keylistener.vcxproj -> C:\projects\harmony\node_modules\mediakeys\build\Release\keylistener.pdb (Full PDB)
gyp
 ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp
 ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! 
stack
     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp
 
ERR!
 System Windows_NT 6.3.9600
gyp
 
ERR!
 
command
 "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp
 
ERR!
 
cwd
 C:\projects\harmony\node_modules\mediakeys
gyp
 
ERR!
 
node -v
 v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by brahiansoto** [comment]
Keyboard shortcuts are working well in Ubuntu 16.04. but the media keys (FN + F10, FN + 11, FN + F12) don't work.

It would be great to have them working since with them you don't have to focus the player's window.

If someone could point me in the right direction... I would like to help

**Comment by vincelwt** [comment]
Should now work on Windows!

**Comment by icd13** [comment]
The version 0.4.2 is not working in my windows 10. Sorry, I can not help you.
