### ISSUE TITLE
Google Play Music incomplete collection

### ISSUE THREAD

**Issue by Feichtmeier** [vincelwt/harmony#150]
Ubuntu 16.04. Unity 7.4
Harmony 0.4.5

The albums from my online collection miss songs and are not complete.

![image](https://cloud.githubusercontent.com/assets/15329494/23238320/af7364bc-f961-11e6-8dae-07087c00c009.png)

**Comment by vincelwt** [comment]
Hi,
Are you using the paid tier of Google Play Music ?
Are you able to find to find similarities behind the tracks not showing? 

It would also be useful to have the log, right after your refresh your music library.
You can find the log by pressing ctrl+alt+i and opening the 'console' tab

**Comment by Feichtmeier** [comment]
Yes I am using the paid tier.
 here is a picture of a log, and an example album where 1 song is missing. I didn't see any similarities. Sometimes 1 sometimes more songs are missing

![image](https://cloud.githubusercontent.com/assets/15329494/23321109/2dea6fc0-fade-11e6-8d98-7eb71dcd773a.png)

**Comment by jessehouwing** [comment]
I have a similar problem on win32 with the latest 0.5 version. The logs don't show anything useful, but from the 37000 tracks on google music, only a fraction is returned:

```
C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7>
[13352:0319/152752.566:INFO:CONSOLE(25)] "We are on a -win32- system", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152752.704:INFO:CONSOLE(25)] "Mediakeys module not found.", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152752.711:INFO:CONSOLE(25)] "ll-keyboard-hook-win module not found.", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152755.130:INFO:CONSOLE(25)] "Testing internet...", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152756.832:INFO:CONSOLE(25)] "Latest release is v0.5.0 and we're running undefined", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152801.558:INFO:CONSOLE(25)] "Fetching services data over.", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152918.634:INFO:CONSOLE(25)] "Testing internet...", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152919.792:INFO:CONSOLE(25)] "Latest release is v0.5.0 and we're running undefined", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
[13352:0319/152922.790:INFO:CONSOLE(25)] "Fetching services data over.", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app\node_modules\console-redirect\index.js (25)
```

Didn't find anything in the logs that makes sense.

**Comment by vincelwt** [comment]
@jessehouwing Are you also using the paid tier of Google Play Music ?

**Comment by jessehouwing** [comment]
I'm using free tier and have a few bought albums.

**Comment by vincelwt** [comment]
@jessehouwing Can you find any pattern with the tracks missing? I really don't see where this is coming from.

also @Feichtmeier what is the approximate size of your library in terms of tracks ?

**Comment by jessehouwing** [comment]
I tried to capture a fiddler trace, but the calls to google music don't seem to flow through the local proxy, I don't see any traffic that indicates funny behavior, other than seeing no traffic at all. I'm using 2FA and an app password, and Google triggers a "New device" warning on my phone the first time I try to sync my library. It looks like about 1000 tracks of the total 32000 have made it through. Only one of the playlists has synced, but it shows only one item of 381. The other 6 playlists all contain 0 items, including the auto-playlists. Is there anything I can do to turn on additional?

**Comment by vincelwt** [comment]
I'm not sure if this is an issue with harmony or the [playmusic module](https://github.com/jamon/playmusic).
The only explanation I see for now is that maybe a Play Music request only returns 1000 tracks but more requests are needed for the rest, like Spotify do for example. I actually just checked and my library (on Harmony) is showing exactly 1000 tracks, which seems like to big of a coincidence. 
That would explain why some of your playlists appear empty, as for free users the playlists tracks are taken from the library.

I'll take a more in depth look at that over the next days, thanks for the help!

**Comment by vincelwt** [comment]
OK after analysing the request, Google indeed returns a 'nextPageToken' for more than 1000 tracks.

**Comment by vincelwt** [comment]
Fixed ;) Thanks to [this issue](https://github.com/jamon/playmusic/issues/40). Will be available with 0.5.1 :)

**Comment by vincelwt** [comment]
Should be ok now with 0.5.1 :)

**Comment by jessehouwing** [comment]
Hmmm... completely broken for me with 0.5.1: 
```
[27808:0326/122650.469:INFO:CONSOLE(25)] "Error fetching data.", source: C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app.asar\node_modules\console-redirect\index.js (25)
```

**Comment by vincelwt** [comment]
@jessehouwing  Could you try resetting your data (settings window) and login again? There was some changes that might need a reset.

**Comment by jessehouwing** [comment]
did a reset. No dice. But I did find a better error message for you:

```
We are on a -win32- system
Testing internet...
Latest release is v0.5.1 and we're running 0.5.1
Error fetching data. Error: error getting library: Error: 500 error from server
    at C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app.asar\node_modules\playmusic\play.js:265:33
    at IncomingMessage.<anonymous> (C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app.asar\node_modules\playmusic\play.js:86:48)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
We are on a -win32- system
Reseting all...
We are on a -win32- system
Testing internet...
Latest release is v0.5.1 and we're running 0.5.1
Error fetching data. Error: error getting library: Error: 500 error from server
    at C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app.asar\node_modules\playmusic\play.js:265:33
    at IncomingMessage.<anonymous> (C:\Users\JesseHouwing\AppData\Local\Programs\Harmony\0.4.7\resources\app.asar\node_modules\playmusic\play.js:86:48)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by Feichtmeier** [comment]
Yay I think it is working! And the unity7 sound menu integration too! Great work!

![image](https://cloud.githubusercontent.com/assets/15329494/24332178/532ed99e-1242-11e7-9951-756f35d5c4bb.png)

**Comment by vincelwt** [comment]
@Feichtmeier Great!

@jessehouwing Hm, seems like an error communicating with the Google servers :/  maybe your library is too big to be sent with one request ? I'm not sure, maybe trying again later will do the trick

**Comment by jessehouwing** [comment]
If you want to do a screenshare in which I give you a temporary google app password, I can do that...

**Comment by jessehouwing** [comment]
@vincelwt tried again today. Logged off, reset, logged on, restarted, used a fresh 2FA token. No dice. Same error as above.

**Comment by vincelwt** [comment]
@jessehouwing I think it should now be fixed as the play music library fixed an error regarding 500 status codes
