### ISSUE TITLE
Soundcloud bug on Windows 8.1

### ISSUE THREAD

**Issue by silverspectro** [vincelwt/harmony#163]
harmony.log

We are on a -win32- system
Mediakeys module not found.
ll-keyboard-hook-win module not found.
We are on a -win32- system
Testing internet...
Latest release is v0.5.0 and we're running undefined
Error fetching data. TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at api.get (C:\Users\Ciro\AppData\Local\Programs\Harmony\0.4.7\resources\app\app\js\plugins\soundcloud.js:55:27)
    at IncomingMessage.<anonymous> (C:\Users\Ciro\AppData\Local\Programs\Harmony\0.4.7\resources\app\app\js\api.js:316:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by vincelwt** [comment]
Hi!
Seems like a network error, is this still happening if you try again to refresh your library?

**Comment by silverspectro** [comment]
It works sometime, and sometime not.
+ i get to enter my credentials really often.

**Comment by vincelwt** [comment]
I see, it seems like SoundCloud sessions expire very quick. I'll see if there a way to obtain a longer valid token from SoundCloud.

**Comment by vincelwt** [comment]
Ok I've switched to non-expiring tokens, login should now not be required so often :)

**Comment by vincelwt** [comment]
Should be ok with 0.5.1!
