### ISSUE TITLE
harmony.json is not created

### ISSUE THREAD

**Issue by yochananmarqos** [vincelwt/harmony#187]
The harmony.json file mentioned below does not exist.

```
~ $ harmony
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/home/yochanan/.config/configstore/harmony.json.1253428018'
You don't have access to this file.

    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Function.writeFileSync [as sync] (/opt/Harmony/resources/app.asar/node_modules/write-file-atomic/index.js:114:17)
    at Configstore.set (/opt/Harmony/resources/app.asar/node_modules/configstore/index.js:62:21)
    at Configstore (/opt/Harmony/resources/app.asar/node_modules/configstore/index.js:27:11)
    at Object.<anonymous> (/opt/Harmony/resources/app.asar/main.js:9:14)
    at Object.<anonymous> (/opt/Harmony/resources/app.asar/main.js:384:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
harmony-0.7.2-x64 (deb)
Linux Mint 18.2

**Comment by vincelwt** [comment]
Seems like Harmony doesn't have sufficient rights to open/create this file, do you have some special permissions on your home folder or .config folder ? 
You can try resetting the permissions of the .config folder and every subfolders.

**Comment by yochananmarqos** [comment]
I just did a fresh install of Mint today, so I don't see how permissions would be screwed up.

```
~ $ ls -la /home/yochanan/.config/Harmony
total 8
drwx------  2 yochanan yochanan 4096 Sep 16 12:21 .
drwxr-xr-x 23 yochanan yochanan 4096 Sep 16 12:21 ..
```

```
~ $ ls -la /home/yochanan/.config/configstore
total 12
drwxr-xr-x  2 root     root     4096 Sep 16 09:10 .
drwxr-xr-x 23 yochanan yochanan 4096 Sep 16 12:21 ..
-rw-------  1 root     root       55 Sep 16 09:10 update-notifier-npm.json
```

**Comment by vincelwt** [comment]
Seems more like an issue with configstore instead of Harmony.
According to [this issue](https://github.com/bower/bower/issues/2262) you can try:

```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```

**Comment by yochananmarqos** [comment]
That worked, thank you!

**Comment by vincelwt** [comment]
Great!
