### ISSUE TITLE
Spotify - Refreshing Failed

### ISSUE THREAD

**Issue by othhho** [vincelwt/harmony#240]

**Comment by othhho** [comment]
<img width="245" alt="Screen Shot 2019-06-10 at 16 01 10" src="https://user-images.githubusercontent.com/25943442/59226603-00baa580-8b99-11e9-9ab3-e3a1fa8fa333.png">

**Comment by vincelwt** [comment]
Could you show what's happening in the logs when it fails? Logs can be shown with Ctrl/Cmd + Alt + i and going to the "console" tab

**Comment by daoktar** [comment]
Same problem, but with local files
```
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading deezer
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading hypem
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading lastfm
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading local
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading playmusic
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading reddit
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading soundcloud
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading spotify
/C:/Program%20Files/Harmony/resources/app.asar/app/js/app.js:76 Loading youtube
/C:/Program%20Files/Harmony/resources/app.asar/app/js/main.js:244 Data not found. Lets refresh.
/C:/Program%20Files/Harmony/resources/app.asar/app/js/main.js:349 Library refresh over.
/C:/Program%20Files/Harmony/resources/app.asar/app/js/main.js:899 Updating service local
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86 Error: FourCC contains invalid characters
    at Object.get (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\music-metadata\lib\common\FourCC.js:14:23)
    at C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\node_modules\strtok3\lib\AbstractTokenizer.js:15:26
    at <anonymous>
mm.parseFile.then.catch.err @ C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:86
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103 Uncaught (in promise) ReferenceError: id is not defined
    at mm.parseFile.then.catch.err (C:\Program Files\Harmony\resources\app.asar\app\js\plugins\harmony-local\index.js:103:11)
    at <anonymous>
Refresh is taking longer than expected...
```

And when press "Retry" i have this in logs:
```
/C:/Program%20Files/Harmony/resources/app.asar/app/#:1 Upcoming versions will block content-initiated top frame navigations to data: URLs. For more information, see https://goo.gl/BaZAea.
main.js:349 Library refresh over.
```
