### ISSUE TITLE
Cannot read property 'tray' of undefined

### ISSUE THREAD

**Issue by binjospookie** [vincelwt/harmony#90]
When launch app
![error](https://theshots.ru/saved/5333559325811ea0040d563.41844094.png)
Ubuntu 16.04

upd: I use mate instead of unity.

**Comment by bswarm9568** [comment]
I'm getting the same error on Ubuntu Gnome 16.04 with gnome-flashback...
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'tray' of undefined
    at App.createWindow (/opt/Harmony/resources/app/main.js:75:27)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

**Comment by vikene** [comment]
I am getting the same with unity on 16.04. But it works fine :+1:

**Comment by vincelwt** [comment]
Ok, I should've fixed it. I'm publishing 0.4.1 so you can try.

**Comment by vincelwt** [comment]
Ok,  just released it, could anyone confirm it's ok with 0.4.1 ?

**Comment by binjospookie** [comment]
It's ok. TY

**Comment by bswarm9568** [comment]
0.4.1 is still not working on Ubuntu Gnome 16.04 with gnome-flashback. I tried removing the package and deleting the leftover Harmony folder in home/config, and reinstalling. All I get is a white window now ...
```
Harmony --enable-logging
[4665:1027/105657:INFO:CONSOLE(26)] "We are on a -linux- system", source: file:///opt/Harmony/resources/app/app/js/app.js (26)
[4665:1027/105657:INFO:CONSOLE(18)] "Mediakeys module not found.", source: file:///opt/Harmony/resources/app/app/js/player.js (18)
[4665:1027/105657:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
[4665:1027/105657:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
[4665:1027/105657:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
[4665:1027/105657:INFO:CONSOLE(2)] "Testing internet...", source: file:///opt/Harmony/resources/app/app/js/utils.js (2)
[4665:1027/105657:INFO:CONSOLE(418)] "listView", source: file:///opt/Harmony/resources/app/app/js/main.js (418)
[4665:1027/105657:INFO:CONSOLE(74)] "Uncaught TypeError: Cannot read property 'playlists' of undefined", source: file:///opt/Harmony/resources/app/app/js/utils.js (74)
Failed to encode dictionary
Failed to encode reply value
Failed to encode dictionary
Failed to encode reply value
[4665:1027/105658:INFO:CONSOLE(253)] "Latest release is v0.4.1 and we're running undefined", source: file:///opt/Harmony/resources/app/app/js/main.js (253)
[4665:1027/105659:INFO:CONSOLE(217)] "Everything over", source: file:///opt/Harmony/resources/app/app/js/main.js (217)
[4665:1027/105659:INFO:CONSOLE(234)] "Error fetching data : undefined", source: file:///opt/Harmony/resources/app/app/js/main.js (234)
[4665:1027/105700:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105700:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105700:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
[4665:1027/105703:INFO:CONSOLE(106)] "Metadatas not found :undefined", source: /opt/Harmony/resources/app/app/js/plugins/local.js (106)
```
